#!/bin/sh

function printMessage()
{
    if [ -z "$1" ]; then
        echo "Usage: printMessage <MESSAGE>" 1>&2
        exit 1
    fi

    local MESSAGE="$1"
    echo -e "$1" 1>&2
}

function printError()
{
    if [ -z "$1" ]; then
        printMessage "Usage: printError <ERRORMESSAGE>"
        exit 1
    fi

    local MESSAGE="$1"
    printMessage "\n***********************************"
    printMessage "$MESSAGE"
    printMessage "***********************************\n"
    ERROR=1
}

function isFile()
{
    if [ -z "$1" ]; then
        printMessage "Usage: isFile <FILE>"
        exit 1
    fi

    FILE="$1"
    if [ ! -z "$(echo $FILE | $GREP "[^/]$")" ]; then
        echo "1"
    else
        echo "0"
    fi
}