#!/bin/bash

#@title Unister Coding Standard
#@author r.lasinski

REPOS="$1"
TXN="$2"

/home/svn_admin/pear/bin/scripts/phpcs-svn-pre-commit-wrapper --standard=UnisterPHP --extensions=php "$REPOS" -t "$TXN" >&2 || exit 1

exit 0