#!/bin/bash

#@title Commit Message
#@author r.lasinski

directory=`dirname $0`
source $directory/../functions/common

############## CONFIG #############
MINLOGLENGTH=6
###################################

REPOS="$1"
TXN="$2"
ERROR=0
SVNLOOK="/usr/bin/svnlook"

LOGMSG=$($SVNLOOK log -t "$TXN" "$REPOS" 2>/dev/null | grep "[a-zA-Z0-9]" | wc -c)

if [ "$LOGMSG" -lt $MINLOGLENGTH ]; then
    printError "Please provide a meaningful comment when committing changes."
fi

# Exit with 0 if no errors, 1 if errors
exit $ERROR