#!/bin/bash

#@title UTF8-BOM forbidden
#@author r.lasinski

directory=`dirname $0`
source $directory/../functions/common

REPOS="$1"
TXN="$2"
ERROR=0

PHP="/usr/bin/php"
SVNLOOK="/usr/bin/svnlook"
AWK="/usr/bin/awk"
GREP="/bin/egrep"
SED="/bin/sed"

function checkBOM()
{
    if [ -z "$1" ]; then
        printMessage "Usage: checkBOM <FILE>"
        exit 1
    fi

    FILE="$1"
    if [ "$(isFile $FILE)" == "1" ] && [ "$($SVNLOOK cat -t "$TXN" "$REPOS" "$FILE" 2>/dev/null | head -c3)" == $'\xef\xbb\xbf' ]; then
        printError "UTF-8 BOM detected in: $FILE"
    fi
}    

#check Commited files
CHANGED=$($SVNLOOK changed -t "$TXN" "$REPOS" 2>/dev/null | $GREP "^[U|A]" | $AWK '{print $2}')
for FILE in $CHANGED; do
    checkBOM "$FILE"
done

# Exit with 0 if no errors, 1 if errors
exit $ERROR